name: Enforce PR label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited]

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@1.0.0
      env:
        VALID_LABELS: bug,enhancement,feature
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}