name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - v3

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}