name: Require PR label

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  require-label:
    runs-on: ubuntu-latest
    id: requirelabel
    steps:
    - uses: yogevbd/require-label-action@master
      with:
        valid-labels: "bug,enhancement,feature"
